#title: AVERtek # your name photo (or website title) here
logo1: "images/BAHAY-LOGO-leaf-green-gold.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br> 
  <b><u>DISCOVER:</u> WHY ALEXAN BAHAY MEANS HOME NOW...
  <br><br> 
  <b><u>ENVISION:</u> 3D Apartment Home from your Computer, Tablet, or Mobile Device</b>Use pointer to rotate & spin; zoom to scale model
  <br><br> 
  <b><u>EXPERIENCE:</u> Augmented Reality (mobile or tablet only)</b>- Scroll down press AR button, place image in open space, anchor on surface, scale & tour apartment
  <br><br>
  <b><u>VIEW:</u></u></b><a href="https://avertek.net/narrative"</b>- See here all that awaits you at Alexan Bahay</a> 
  <br><br>
  <b><u>EXPLORE:</u></u></b><a href="https://avertek.net/narrative"</b>- Alexan Bahay for yourself, click here for a self-guided or in-person private tour & receive a special gift</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
