#title: AVERtek # your name photo (or website title) here
logo1: "images/BAHAY-LOGO-leaf-green-gold.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p style="text-align:center;"><h1><b>MEANS HOME</h1></b>
  <h2><b>Engage ALL 4 Experiences</h2></b>
  <br><br>
  <h3><b>ENVISION: 3D APARTMENT MODEL </h3></b>
  <br><br> 
  <h3><b>EXPLORE: MOBILE 4D AUGMENTED REALITY</h3></b>
  <br><br>
  <h3><a href="https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR'); return false;"<b> VIEW LUXURY LIVING</h3></b></a> 
  <br><br>
  <h3><a href="https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR'); return false;"<b> DISCOVER VIP TOUR; FREE GIFT</h3></b></a></p> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-188164724-2 
