#title: AVERtek # your name photo (or website title) here
logo1: "images/BAHAY-LOGO-leaf-green-gold.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br> 
  <h1><b>ALEXAN BAHAY MEANS HOME</h1></b>
  <h2><b>Engage ALL 4 Experiences</h2></b>
  <br><br>
  <b>ENVISION: 3D APARTMENT MODEL </b>  Tour 3D Model on Computer
  <br><br> 
  <b>EXPLORE: 4D AUGMENTED REALITY</b>  AR Walking Tour on Mobile Device
  <br><br>
  <b>VIEW:</b><a href="https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR'); return false;"</b><b> LUXURY LIVING</b></a> 
  <br><br>
  <b>DISCOVER:</b><a href="https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR'); return false;"</b> <b> VIP TOUR & FREE GIFT</a> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-188164724-2 
