#title: AVERtek # your name photo (or website title) here
logo1: "images/BAHAY-LOGO-leaf-green-gold.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="color:#A28D5B;"><p style="text-align:center;"><b>MEANS HOME</h1></b></p>
  <br><br> 
  <h2 style="text-align: center;" markdown="1"><b>LIFESTYLE</b><a href="https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR'); return false;"<b> EXPERIENCE</b></h2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>THE 360</b><a href="https://alexanbahay.com/gallery/apartment-tours/" onclick="getOutboundLink('https://alexanbahay.com/gallery/apartment-tours/'); return false;"<b> EXPERIENCE</b><h/2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>FLOORPLAN WALK-ABOUT</b><a href="https://avertek.github.io/Alexan-Bahay-1Bd-2/" onclick="getOutboundLink('https://avertek.github.io/Alexan-Bahay-1Bd-2/'); return false;"<b> 4D/AR EXPERIENCE</b></h2></a> 
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>SIGN-UP FOR PERSONAL:</b><a href="https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR'); return false;"<b> TOUR & DRAWING</b></h2></a> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-188164724-1 
