#title: AVERtek # your name photo (or website title) here
logo1: "images/BAHAY-LOGO-leaf-green-gold.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="color:#A28D5B;"><p style="text-align:center;"><b>MEANS HOME</h1></b></p>
  <h2 style="color:#215732;"><em><p style="text-align:center;"><b>LA's Iconic Echo Park Near Dodger Stadium</h2></em></b></p>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>LIFESTYLE</b><a href="https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/gallery/video/?utm_source=AVERtek&utm_medium=AR'); return false;"<b> EXPERIENCE</b></h2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>THE 360</b><a href="https://alexanbahay.com/gallery/apartment-tours/" onclick="getOutboundLink('https://alexanbahay.com/gallery/apartment-tours/'); return false;"<b> ENCOUNTER</b><h/2></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>TRANSPORT TO THE</b><a href="https://avertek.github.io/Alexan-Bahay-1Bd-2/" onclick="getOutboundLink('https://avertek.github.io/Alexan-Bahay-1Bd-2/'); return false;"<b> 4D/AR FLOORPLAN</b></h2></a> 
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>SIGN-UP FOR PERSONAL</b><a href="https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR'); return false;"<b> TOUR & DRAWING</b></h2></a> 
  <br><br>
  <br>
  <h2 style="text-align: center;" markdown="1"><a href="tel:+18333101450"><b>833-310-1450</a></b></h2>
  <h2 style="text-align: center;" markdown="1"><b>EMAIL US:</b><a href="mailto:mailto:AlexanBahay.AVERtek.SaresRegis@aptleasing.info?Subject=VIP TOUR & DRAWING" onclick="getOutboundLink('mailto:mailto:AlexanBahay.AVERtek.SaresRegis@aptleasing.info'); return false;"<b> VIP TOUR & DRAWING</b></h2></a> 
  <h2 style="color:#215732;"><p style="text-align:center;"><b>330 N Westlake Ave., Los Angeles, CA 90026</h2></b></p>
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-188164724-1 
